# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b787272682c8fb76aaa2709749f291216148f1c589bf79de6753fd9f96634858f6f9e35baf5c0e4dd9e40bfb5d64594a2f0f719a6b98dca9de012928c6308753

test:
  secret_key_base: 35bc71cc04f2c52f1072470fa335f09a7067a787c0aec0e0d94d39219838600f0de70f7a905b080e9436811870feeb9c1731fbaece040408d5b6a54005ef6e37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
